import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: '@aiadevop',
  description: 'Generated by Lara Alonso',
}

export default function RootLayout({ children }) {
  return (    
    <html lang="es">
      <head></head>
      <body className={inter.className} suppressHydrationWarning={true} > 
        {children}
      </body>
    </html>
  )
}
